name: Run Robot Framework Tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-robot-framework-tests:
    runs-on: ubuntu-latest
    steps:
    # Checks-out the tests repository under $GITHUB_WORKSPACE
      - name: Checkout Tests Repository
        uses: actions/checkout@v2

    
    # Upload Robot Framework report folder as an artifact zip folder
      - name: Upload test reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test Report
          # set path to Robot Framework results report.
          path: ${{ github.workspace }}/output
          
    - name: Send email
        uses: devellany/send-mail@v1.0.2
        with:
            host: smtp.gmail.com
            account: hf.carlsberg
            password: QhIUHnroOxklhs0T9vJE
            sender: devellany
            from: hugo.fernandes@carlsberg.com
            subject: Github Actions job result
            body: test
            #attachments: '[{"path":"README.md"}]'
            to: hugo.fernandes@boost-it.pt
                  

