name: Run Robot Framework Tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-robot-framework-tests:
    runs-on: ubuntu-latest
    steps:
    # Checks-out the tests repository under $GITHUB_WORKSPACE
      - name: Checkout Tests Repository
        uses: actions/checkout@v2

    
    # Upload Robot Framework report folder as an artifact zip folder
      - name: Upload test reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test Report
          # set path to Robot Framework results report.
          path: ${{ github.workspace }}/output
          
      - name: Send mail
        uses: dawidd6/action-send-mail@v3.1.0
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
        # Required mail server port:
          server_port: 465
        # Required mail server username:
          username: hf.carlsberg@gmail.com
        # Required mail server password:
          password: QhIUHnroOxklhs0T9vJE
        # Required mail subject:
          subject: Github Actions job result
        # Required recipients' addresses:
          to: hugo.fernandes@boost-it.pt
        # Required sender full name (address can be skipped):
          from: hf.carlsberg@gmail.com
        # Optional whether this connection use TLS (default is true if server_port is 465)
          #secure: true
        # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
        # Optional unsigned/invalid certificates allowance:
          #ignore_cert: true
